/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_BASE_URL || 'https://www.louwill.com',
  generateRobotsTxt: false, // We have custom robots.ts
  exclude: ['/admin', '/admin/*', '/auth/*', '/api/*'],
  additionalPaths: async (config) => {
    // For now, return static paths. Dynamic paths will be generated by Next.js sitemap.ts
    return [
      {
        loc: '/blog/welcome-to-my-tech-blog',
        changefreq: 'weekly',
        priority: 0.8,
        lastmod: new Date().toISOString()
      }
    ]
  },
  transform: async (config, path) => {
    // Custom priority and frequency based on path
    if (path === '/') {
      return {
        loc: path,
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString()
      }
    }
    
    if (path === '/blog') {
      return {
        loc: path,
        changefreq: 'daily',
        priority: 0.9,
        lastmod: new Date().toISOString()
      }
    }
    
    if (path === '/about') {
      return {
        loc: path,
        changefreq: 'monthly',
        priority: 0.7,
        lastmod: new Date().toISOString()
      }
    }
    
    return {
      loc: path,
      changefreq: 'weekly',
      priority: 0.5,
      lastmod: new Date().toISOString()
    }
  }
}